core/urls.py
from django.urls import path

from core.views import (
    index,
    DishListView,
    DishTypeListView,
    CountryListView,
    CookListView,
    CookDetailView,
    CountryDetailView,
    DishDetaiView,
    DishTypeDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetaiView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete", DishDeleteView.as_view(), name="dish-delete"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("countries/", CountryListView.as_view(), name="country-list"),
    path("countries/<int:pk>/", CountryDetailView.as_view(), name="country-detail"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "core"

international_kitchen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", logout_view, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.conf import settings
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.SET_NULL,
        related_name="dishes", null=True
    )
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} - {self.price}. Dish type:{self.dish_type.name}"


class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "country"
        verbose_name_plural = "countries"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0)]
    )
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    info = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("core:cook-detail", kwargs={"pk": self.pk})

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


from core.models import Dish, Cook


class DishForm(forms.ModelForm):
    MIN_PRICE = 5

    class Meta:
        model = Dish
        fields = (
            "name",
            "description",
            "price",
            "dish_type",
            "cooks",
            "available",
        )

    def clean_price(self):
        price = self.cleaned_data["price"]
        if price < self.MIN_PRICE:
            raise forms.ValidationError(
                f"Ensure the price is >= {DishForm.MIN_PRICE}"
            )
        return price


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "years_of_experience", "country",
        )


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ("first_name", "years_of_experience", "country")

    def clean_years_of_experience(self):
        return self.cleaned_data["years_of_experience"]


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish name",
            }
        )
    )

core/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from core.forms import (
    DishForm,
    CookCreationForm,
    CookUpdateForm,
    DishSearchForm
)
from core.models import (
    Cook,
    Dish,
    DishType,
    Country
)


def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()
    num_countries = Country.objects.count()

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_countries": num_countries,
    }

    return render(request, "core/index.html", context=context)


class DishListView(generic.ListView):
    model = Dish
    queryset = Dish.objects.all()
    paginate_by = 8
    template_name = "core/dish_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetaiView(generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("core:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("core:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "core/dish_confirm_delete.html"
    success_url = reverse_lazy("core:dish-list")


class DishTypeListView(generic.ListView):
    model = DishType
    template_name = "core/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5


class DishTypeDetailView(generic.DetailView):
    model = DishType
    template_name = "core/dish_type_detail.html"
    context_object_name = "dish_type"
    paginate_by = 5


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("core:dish-type-list")
    template_name = "core/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("core:dish-type-list")
    template_name = "core/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "core/dish_type_confirm_delete.html"
    success_url = reverse_lazy("core:dish-type-list")


class CountryListView(generic.ListView):
    model = Country
    paginate_by = 10


class CountryDetailView(generic.DetailView):
    model = Country


class CookListView(generic.ListView):
    model = Cook
    paginate_by = 5

    def get_queryset(self):
        return Cook.objects.order_by("first_name")


class CookDetailView(generic.DetailView):
    model = Cook


class CookCreateView(generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("core:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("core:cook-list")


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return render(request, "registration/logged_out.html")

templates/core/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are sure you want to delete info about Chef?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/core/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Name: {{ cook.first_name }} {{ cook.last_name }}
    <a href="{% url 'core:cook-update' pk=cook.id %}" class="btn btn-danger link-to-page">
      Update
    </a>

    <a href="{% url 'core:cook-delete' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Delete
    </a>
  </h1>
  
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
  <p><strong>Origin:</strong> {{ cook.country }}</p>
  
{% endblock %}

templates/core/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Chef</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/core/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
      Our amazing chefs:
      <a href="{% url 'core:cook-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>
  
  {% if cook_list %}
    <ul>
      {% for cook in cook_list %}
        <li><a href="{% url 'core:cook-detail' pk=cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a> - {{ cook.country }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/core/country_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Country: {{ country.name }}

  </h1>
  <br>
  
  <p><strong>About:</strong> {{ country.description }}</p>
  
{% endblock %}

templates/core/country_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Global Recipes from Our Talented International Chefs</h1>
  <p>Countries list:</p>
  {% if country_list %}
    <ul>
      {% for country in country_list %}
        <li><a href="{% url 'core:country-detail' pk=country.id %}">{{ country.name }} - {{ country.description }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock %}

templates/core/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Would you like to delete this dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/core/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish: {{ dish.name }} - {{ dish.price }}
    <a href="{% url 'core:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'core:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <br>
  
  <p><strong>About:</strong> {{ dish.description }}</p>
  
{% endblock %}

templates/core/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/core/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1> Dish List
  <a href="{% url 'core:dish-create' %}" class="btn btn-primary link-to-page">
    Create</a>
  </h1>
  
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  
  
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Dish type</th>
        <th>Cooks</th>
        <th>Available</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    
      {% for dish in dish_list %}
        <tr>
          <td>
              {{ dish.name }}
          </td>
          <td>
              {{ dish.price }}
          </td>
          <td>
              {{ dish.dish_type }}
          </td>
          <td>
              {% for cook in dish.cooks.all %}
                <a href="{{ cook.get_absolute_url }}">{{ cook.first_name }} {{ cook.last_name }}</a>{% if not forloop.last %}, {% endif %}
              {% empty %}
                No cooks assigned
            {% endfor %}
          </td>
          <td>
              {{ dish.available }}
          </td>
        
        <td>
              <a href="{% url 'core:dish-detail' pk=dish.id %}">
                see more👌🏼
              </a>
            </td>
        
          <td>
              <a href="{% url 'core:dish-update' pk=dish.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'core:dish-delete' pk=dish.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There is no dishes.</p>
  {% endif %}
{% endblock %}

templates/core/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Would you like to delete this dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/core/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish: {{ dish_type.name }}

  </h1>
  <br>
  
  <p><strong>About:</strong> {{ dish_type.description }}</p>
  
{% endblock %}

templates/core/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish-types List
    <a href="{% url 'core:dish-type-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  
  
  {% if dish_type_list %}
    <table class="table">
    <tr>
        <th>Name</th>
        <th>About</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    
      {% for dish_type in dish_type_list %}
        <tr>
          <td>
              {{ dish_type.name }}
          </td>
          <td>
              <a href="{% url 'core:dish-type-detail' pk=dish_type.id %}">
                See more
              </a>
            </td>
          <td>
              <a href="{% url 'core:dish-type-update' pk=dish_type.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'core:dish-type-delete' pk=dish_type.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There is no dish-types in the service.</p>
  {% endif %}
{% endblock %}

templates/core/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="content-overlay">
    <h1>Welcome To International Kitchen</h1>
    <img src="{% static 'images/111.jpg' %}" alt="restaurant" class="header-image" style="max-width: 12%; height: auto;" />
    <img src="{% static 'images/222.jpg' %}" alt="restaurant" class="header-image" style="max-width: 12%; height: auto;" />
    <img src="{% static 'images/555.jpg' %}" alt="restaurant" class="header-image" style="max-width: 12%; height: auto;" />
    
    <p>Discover Unique Recipes from Our Chefs Around the World!</p>
    <h2>Experience Culinary Journey:</h2>
    <p>Indulge in a culinary experience like no other at our exquisite restaurant, where talented chefs from <br>
  around the globe craft authentic dishes that celebrate diverse flavors and traditions. <br>
  Experience a symphony of tastes that transcend borders, ensuring every visit is a feast for the senses.</p>
    <ul>
      <li><strong>Dish Types:</strong> {{ num_dish_types }}</li>
      <li><strong>Dishes:</strong> {{ num_dishes }}</li>
      <li><strong>Cooks:</strong> {{ num_cooks }}</li>
      <li><strong>Culinary Traditions from Around the World:</strong> {{ num_countries }}</li>
    </ul>
    <p>Authentic Dishes Crafted by Chefs from Around the Globe!</p>
  </div>
{% endblock %}